################ English language ##################
[en]
languageName = "en"
languageCode = "en-us"
contentDir = "content/english"
weight = 1

################ French language ##################
[fr]
languageName = "fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 1
